import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/config/providers";
import { getAllCategories, getProfile } from "@/lib/api";
import Header from "@/components/Header";
import { CategoryDto, UserInfoDto } from "@/generated/openapi-client";
import { Toaster } from "sonner";
import { auth } from "@/auth";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [session, profile, categories] = await Promise.all([
    auth(),
    getProfile(),
    getAllCategories(),
  ]);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-7xl mx-auto`}
      >
        <Providers>
          <Header
            session={session}
            categories={categories.data ?? ([] as CategoryDto[])}
            profile={profile.data ?? ({} as UserInfoDto)}
          />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
